# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'icerikekle.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(426, 729)
        self.aciklama = QtWidgets.QPlainTextEdit(Form)
        self.aciklama.setGeometry(QtCore.QRect(13, 20, 401, 561))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.aciklama.setFont(font)
        self.aciklama.setObjectName("aciklama")
        self.sayfa = QtWidgets.QLabel(Form)
        self.sayfa.setGeometry(QtCore.QRect(170, 680, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sayfa.setFont(font)
        self.sayfa.setObjectName("sayfa")
        self.oncekiButon = QtWidgets.QPushButton(Form)
        self.oncekiButon.setGeometry(QtCore.QRect(30, 610, 51, 41))
        self.oncekiButon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/sol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.oncekiButon.setIcon(icon)
        self.oncekiButon.setIconSize(QtCore.QSize(32, 32))
        self.oncekiButon.setObjectName("oncekiButon")
        self.sonrakiButon = QtWidgets.QPushButton(Form)
        self.sonrakiButon.setGeometry(QtCore.QRect(140, 610, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.sonrakiButon.setFont(font)
        self.sonrakiButon.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui/sağ.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sonrakiButon.setIcon(icon1)
        self.sonrakiButon.setIconSize(QtCore.QSize(32, 32))
        self.sonrakiButon.setObjectName("sonrakiButon")
        self.kaydetButon = QtWidgets.QPushButton(Form)
        self.kaydetButon.setEnabled(False)
        self.kaydetButon.setGeometry(QtCore.QRect(290, 610, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.kaydetButon.setFont(font)
        self.kaydetButon.setObjectName("kaydetButon")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "İçerik Ekle"))
        self.sayfa.setText(_translate("Form", "Sayfa : 5"))
        self.kaydetButon.setText(_translate("Form", "Kaydet"))
