from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(424, 735)
        Form.setStyleSheet("background-color: yellow;")  # Arka plan rengi sarı olarak değiştirildi
        self.aciklamaLabel = QtWidgets.QLabel(Form)
        self.aciklamaLabel.setGeometry(QtCore.QRect(20, 20, 381, 571))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.aciklamaLabel.setFont(font)
        self.aciklamaLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.aciklamaLabel.setScaledContents(False)
        self.aciklamaLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.aciklamaLabel.setWordWrap(True)
        self.aciklamaLabel.setObjectName("aciklamaLabel")
        self.oncekiButon = QtWidgets.QPushButton(Form)
        self.oncekiButon.setGeometry(QtCore.QRect(90, 610, 51, 41))
        self.oncekiButon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/sol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.oncekiButon.setIcon(icon)
        self.oncekiButon.setIconSize(QtCore.QSize(32, 32))
        self.oncekiButon.setObjectName("oncekiButon")
        self.sonrakiButon = QtWidgets.QPushButton(Form)
        self.sonrakiButon.setGeometry(QtCore.QRect(270, 610, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.sonrakiButon.setFont(font)
        self.sonrakiButon.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui/sağ.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sonrakiButon.setIcon(icon1)
        self.sonrakiButon.setIconSize(QtCore.QSize(32, 32))
        self.sonrakiButon.setObjectName("sonrakiButon")
        self.sayfa = QtWidgets.QLabel(Form)
        self.sayfa.setGeometry(QtCore.QRect(170, 660, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.sayfa.setFont(font)
        self.sayfa.setObjectName("sayfa")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Kitap Okuma"))
        self.aciklamaLabel.setText(_translate("Form", "<html><head/><body><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nunc odio, blandit in sodales pharetra, suscipit id nunc. Sed a scelerisque nisi, vitae dapibus velit. Nulla neque mauris, congue at augue sit amet, consequat vehicula metus. Maecenas viverra sit amet mauris ut cursus. Nulla et vehicula nisi. Morbi in aliquam nunc. Pellentesque ut congue risus, non molestie neque. Maecenas sed sollicitudin arcu. In in libero non quam fermentum lobortis in sit amet felis.</p><p>Sed pulvinar rhoncus felis quis fermentum. Sed efficitur ligula placerat felis scelerisque, vel finibus metus fermentum. Nullam interdum sapien a sollicitudin dictum. Maecenas dictum nulla mi, eu finibus felis ullamcorper vitae. Nulla at faucibus augue. Ut tristique aliquet vehicula. Proin non gravida velit, sed fermentum arcu. Aenean vulputate hendrerit lorem, sed convallis justo ullamcorper sed. Nullam varius maximus tincidunt. Vestibulum mollis felis non enim malesuada congue. Donec aliquam rutrum semper. Vestibulum eu. </p></body></html>"))
        self.sayfa.setText(_translate("Form", "Sayfa : 5"))
