from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(476, 366)
        Form.setStyleSheet("background-color: #40E0D0;")  # Arka plan rengi turkuaz olarak değiştirildi
        self.tablo = QtWidgets.QTableWidget(Form)
        self.tablo.setGeometry(QtCore.QRect(0, 0, 471, 161))
        self.tablo.setObjectName("tablo")
        self.tablo.setColumnCount(2)
        self.tablo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(1, item)
        self.yorumText = QtWidgets.QTextEdit(Form)
        self.yorumText.setGeometry(QtCore.QRect(30, 220, 421, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.yorumText.setFont(font)
        self.yorumText.setStyleSheet("background-color: white;")
        self.yorumText.setObjectName("yorumText")
        self.yorumYapButon = QtWidgets.QPushButton(Form)
        self.yorumYapButon.setGeometry(QtCore.QRect(160, 310, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.yorumYapButon.setFont(font)
        self.yorumYapButon.setStyleSheet("background-color: #2c3e50; color: white;")
        self.yorumYapButon.setObjectName("yorumYapButon")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(180, 180, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Yorumlar"))
        item = self.tablo.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Kullanıcı"))
        item = self.tablo.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Yorum"))
        self.yorumYapButon.setText(_translate("Form", "Yorum Yap"))
        self.label.setText(_translate("Form", "Yorum Yaz"))
